language: node_js
node_js:
    - lts/*
script:
    - npm run test
    - npm run build
deploy:
    - provider: script
      script: npx --package @dhis2/deploy-build deploy-build
      skip_cleanup: true
      on:
          tags: false
          all_branches: true
env:
    global:
        secure: dvW9G0a82RuWS94kEnUXTqrecdjSTJ7LYTpTAX9G2gFXuKON6sm5qs6Kc2wMrd69CpY/ns7P7shJVt27oERunK+ZGhnC//inF6D6QHjUrCK3u0xlRdpduh9wFIqX7s+5/eXSPFjEnNe2KF9jlQIzdwQrgOxHdSu8yjzOICgj4+eomqWE9e8p3+DdFasNs7OyQaoNFyfogmbOzljmsWvYqnSqAVwDca/QjCOoYamE6fU5QOrttLGC39a/gdLOzXqjY5cw1+652jKBMfpPVzVo4U+wg+ZvQ0bC8AYjb0r13QRtF6Mdos629mTk9D8z6fdkFIA8OMwnuG5dpvjwHVPQ8ZIsbnRBaVsgB9OQJDGwHXhxOPrxKufx5DeKOuXtWCLje9flHsNbjCYpU0e7pltCWEwOxKiJW1f6NRhMyU3+pOPOFPtG8EsD3rwMgiE6My1ofM67sWIuoXMOcDjq5kcH9b8Z9XS4L/8m7M/g1y8VQ48ntG1rIEfpEVZaUYmk0PD5DqgJOMh4nQmgO2qXVCy1/8HQwaXedCJorkd3bRixkL0WNsT2g+SIuz6O/re8OTx62UhPYwvWd/p6Bb4HlOMgF/uZRSttXPV4LWAhWMIJRptOoI6Ok6D+NAwTbb1hUAP2JsGl1heLWkcqTyJwqTmJVkx7pOCO26b4xT8exJwSeGA=
