language: node_js
node_js:
- '8'
env:
  global:
  - CC_TEST_REPORTER_ID=b5a1d0f16f3e13f021ec67a70d745c24615a027745dea04e5a603af230fa4fef
  - secure: dvW9G0a82RuWS94kEnUXTqrecdjSTJ7LYTpTAX9G2gFXuKON6sm5qs6Kc2wMrd69CpY/ns7P7shJVt27oERunK+ZGhnC//inF6D6QHjUrCK3u0xlRdpduh9wFIqX7s+5/eXSPFjEnNe2KF9jlQIzdwQrgOxHdSu8yjzOICgj4+eomqWE9e8p3+DdFasNs7OyQaoNFyfogmbOzljmsWvYqnSqAVwDca/QjCOoYamE6fU5QOrttLGC39a/gdLOzXqjY5cw1+652jKBMfpPVzVo4U+wg+ZvQ0bC8AYjb0r13QRtF6Mdos629mTk9D8z6fdkFIA8OMwnuG5dpvjwHVPQ8ZIsbnRBaVsgB9OQJDGwHXhxOPrxKufx5DeKOuXtWCLje9flHsNbjCYpU0e7pltCWEwOxKiJW1f6NRhMyU3+pOPOFPtG8EsD3rwMgiE6My1ofM67sWIuoXMOcDjq5kcH9b8Z9XS4L/8m7M/g1y8VQ48ntG1rIEfpEVZaUYmk0PD5DqgJOMh4nQmgO2qXVCy1/8HQwaXedCJorkd3bRixkL0WNsT2g+SIuz6O/re8OTx62UhPYwvWd/p6Bb4HlOMgF/uZRSttXPV4LWAhWMIJRptOoI6Ok6D+NAwTbb1hUAP2JsGl1heLWkcqTyJwqTmJVkx7pOCO26b4xT8exJwSeGA=
before_script:
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
  > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- "./cc-test-reporter before-build"
script:
- npm run build
- npm run deploy
after_script:
- "./cc-test-reporter after-build -d --exit-code $TRAVIS_TEST_RESULT"
